### ISSUE TITLE
Unpublished apple-api-types 1.3.4?

### ISSUE THREAD

**Issue by ondrejbohac** [jeremybarbet/iap#2]
Hello,

I have problem with installation latest nest-iap (1.3.4), yarn is missing version for package apple-api-types 1.3.4 and gives me choice to install older versions.

I think there is some problem with publication that version? 

I have no problem with installing nest-iap 1.3.3.

Thank you

**Comment by jeremybarbet** [comment]
Hey! 

Thanks for the heads-up I didn't even realised it failed to publish through npm. I will do a manual retry tonight. I will update this ticket once done.

**Comment by jeremybarbet** [comment]
Couldn't publish 1.3.4 for this package, npm complaining this version has been already published, which wasn't. Already got the issue before and I'm not really sure if it's coming from lerna doing something weird, or something I am missing.

Anyway, 1.3.5 published for all packages

**Comment by ondrejbohac** [comment]
Thank you 👍
