### ISSUE TITLE
Given Google purchaseToken, can I get purchased amount?

### ISSUE THREAD

**Issue by 94929** [jeremybarbet/iap#5]
As above. Thanks in advance!

**Comment by jeremybarbet** [comment]
- yes for: [purchases.subscriptions.get](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions#SubscriptionPurchase)
- no for: [purchases.products.get](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products#ProductPurchase)
- not sure for: [purchases.subscriptionsv2.get](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2/get)
